### ISSUE TITLE
Wasm module compile error in Chrome Extension

### ISSUE THREAD

**Issue by p-mazhnik** [motiko/kcr-translate-ext#12]
Created from A Google User's review from Jan 12, 2022 at [Chrome Store](https://chrome.google.com/webstore/detail/kindle-cloud-reader-trans/ipalacjfeejceeogpnfaijpadginmfhk?hl=en):  

>:: ONLY A PROBLEM IN BASED CHROMIUM BROWSERS ::
I had to download the extension instead of install it and modify the manifest.js file to include this line:  
>
>"content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'"
>
>after that I needed reload the extension in the browser with develop mode and works fine.
>
>This article details the problem:
https://stackoverflow.com/questions/48523118/wasm-module-compile-error-in-chrome-extension

**Comment by p-mazhnik** [comment]
Note that Chrome will stop `Manifest V2` extensions from January 2023, and `V3` extensions are not allowed to use `unsafe-eval` in the `content_security_policy`.

**Comment by motiko** [comment]
Works now with `asm.js` tesseract
