### ISSUE TITLE
Add an easy option to disable extension

### ISSUE THREAD

**Issue by motiko** [motiko/kcr-translate-ext#15]
As requested here
![image](https://user-images.githubusercontent.com/875618/150630432-e72436e3-8f5f-4456-b957-314e4e24a887.png)

**Comment by p-mazhnik** [comment]
This feature really similar to the following changes:
https://github.com/motiko/kcr-translate-ext/pull/11

**Comment by motiko** [comment]
I will test it now and make a new version release then. (somehow forgot about this one sorry)
Would it also work for people how don't use google translate extension?

**Comment by p-mazhnik** [comment]
No, in order to use `Google Translation Extension engine` you need to install `google translate extension` first.
I should have added this information to the `options`
