### ISSUE TITLE
Support content scripts reloading

### ISSUE THREAD

**Issue by p-mazhnik** [motiko/kcr-translate-ext#21]
Our content scripts (`index.js` and `autoplay.js`) can be reloaded while the user is working. Currently it happens if the user updated settings using `popup` (but I think there may be other situations). 
Currently after each reload there will be multiple of the same listeners, observers, iframe, etc.

We need to fix this and remove listeners before reloading

**Comment by motiko** [comment]
We might not need to reload the script at all. Instead we can read the settings at action time (eg mouseUp) instead. WDYT?

**Comment by motiko** [comment]
Removing listeners on unload would still be good for reducing memory usage in cases user navigates between books. We have to test this.

**Comment by p-mazhnik** [comment]
Currently working on this

**Comment by motiko** [comment]
OK cool, let me know if you need anything. I will wait for this to release 0.3.2
