### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by load4000** [motiko/kcr-translate-ext#3]
[Deprecation] Application Cache API manifest selection is deprecated and will be removed in M82, around April 2020. See https://www.chromestatus.com/features/6192449487634432 for more details.
?asin=B0192CTMVY:1 Document was loaded from Application Cache with manifest https://read.amazon.com/offline/cache.manifest
?asin=B0192CTMVY:1 Application Cache Checking event
DevTools failed to parse SourceMap: chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.preload.js.map
DevTools failed to parse SourceMap: chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map
DevTools failed to parse SourceMap: chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.postload.js.map
DevTools failed to parse SourceMap: chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map
KindleApp-min.js:36 [Deprecation] Application Cache API use is deprecated and will be removed in M82, around April 2020. See https://www.chromestatus.com/features/6192449487634432 for more details.
initialize @ KindleApp-min.js:36
a @ KindleApp-min.js:37
e @ KindleApp-min.js:37
(anonymous) @ KindleApp-min.js:312
o @ KindleCommon.js:3
add @ KindleCommon.js:3
then @ KindleCommon.js:3
define @ KindleApp-min.js:312
initialize @ KindleApp-min.js:38
initialize @ KindleApp-min.js:83
im @ chext_driver.js:49
x.M @ chext_driver.js:483
Q.ha @ chext_driver.js:317
R @ chext_driver.js:78
x.M @ chext_driver.js:472
Q.ha @ chext_driver.js:317
R @ chext_driver.js:78
x.M @ chext_driver.js:484
Q.ha @ chext_driver.js:317
(anonymous) @ chext_driver.js:393
E @ chext_driver.js:256
x.M @ chext_driver.js:393
Q.ha @ chext_driver.js:317
R @ chext_driver.js:78
x.M @ chext_driver.js:505
Q.ha @ chext_driver.js:317
R @ chext_driver.js:78
Xz @ chext_driver.js:238
Yz @ chext_driver.js:238
dA @ chext_driver.js:240
(anonymous) @ chext_driver.js:563
(anonymous) @ chext_driver.js:566
load (async)
(anonymous) @ ?asin=B0192CTMVY:52
Show 2 more frames
DevTools failed to parse SourceMap: chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.preload.js.map
DevTools failed to parse SourceMap: chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map
DevTools failed to parse SourceMap: chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.preload.js.map
DevTools failed to parse SourceMap: chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map
DevTools failed to parse SourceMap: chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.postload.js.map
DevTools failed to parse SourceMap: chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map
?asin=B0192CTMVY:1 Application Cache NoUpdate event
DevTools failed to parse SourceMap: chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.preload.js.map
DevTools failed to parse SourceMap: chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map
DevTools failed to parse SourceMap: chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.postload.js.map
DevTools failed to parse SourceMap: chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map
KindleApp-min.js:48 hiding library
DevTools failed to parse SourceMap: chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.preload.js.map
DevTools failed to parse SourceMap: chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map
DevTools failed to parse SourceMap: chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.preload.js.map
DevTools failed to parse SourceMap: chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map
DevTools failed to parse SourceMap: chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.preload.js.map
DevTools failed to parse SourceMap: chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map
DevTools failed to parse SourceMap: chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.preload.js.map
DevTools failed to parse SourceMap: chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map
DevTools failed to parse SourceMap: chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.postload.js.map
DevTools failed to parse SourceMap: chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map
DevTools failed to parse SourceMap: chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.postload.js.map
DevTools failed to parse SourceMap: chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map

**Comment by mwjones** [comment]
Just tried the extension and mine, too, does not work.  I too have warnings about the AppCache in the console.  MacOs Mojave 10.14.6

**Comment by motiko** [comment]
thank you for reporting
has been fixed in 0.2.0
0.2.0 is using OCR to extract text (with tesseract lib)
if you encounter problems with new version please open a new issue.
