### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by dzmitryv** [motiko/kcr-translate-ext#32]
I don't think the extension still works with Kindle Cloud Reader. I installed the extension, when I select text just usual cloud reader options appear, no Google Translate translation.

- Single word selection shows Kindle provided dictionary https://prnt.sc/xk7h4nY9EF3D
- Multi word selection shows highlight and "take note" options https://prnt.sc/uqKy7V7bUZSV

**Comment by motiko** [comment]
Should work in 0.3.3
Let me know if you still encounter any problems.
