### ISSUE TITLE
Kindle cloud translate don´t working for three days

### ISSUE THREAD

**Issue by erata** [motiko/kcr-translate-ext#6]
thanks for this valuable extension.
it has not worked for three days.
 there is an message on console as below:

> Kindle Readed Widnow not found: trying again in 1 second..

thanks.

**Comment by motiko** [comment]
thank you for reporting
has been fixed in 0.2.0 
0.2.0 is using OCR to extract text (with tesseract lib)
if you encounter problems with new version please open a new issue.
